-- V1__init.sql (MySQL)
-- UUIDs are stored as CHAR(36) and generated by Hibernate in Java (see the
-- @JdbcTypeCode(SqlTypes.CHAR) annotation on each entity's @Id field) rather
-- than by the database, since MySQL has no native UUID type or default
-- UUID-generating expression the way Postgres's gen_random_uuid() does.

CREATE TABLE users (
  id CHAR(36) PRIMARY KEY,
  name VARCHAR(120) NOT NULL,
  email VARCHAR(160) UNIQUE NOT NULL,
  password_hash VARCHAR(255) NOT NULL,
  role VARCHAR(20) NOT NULL CHECK (role IN ('STUDENT','FACULTY','ADMIN')),
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE question_templates (
  id CHAR(36) PRIMARY KEY,
  subject VARCHAR(80) NOT NULL,
  topic VARCHAR(80) NOT NULL,
  template_text TEXT NOT NULL,
  formula_key VARCHAR(80) NOT NULL,
  variable_rules JSON NOT NULL,
  difficulty VARCHAR(20) DEFAULT 'MEDIUM',
  created_by CHAR(36),
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (created_by) REFERENCES users(id)
);

CREATE TABLE exams (
  id CHAR(36) PRIMARY KEY,
  title VARCHAR(160) NOT NULL,
  subject VARCHAR(80) NOT NULL,
  duration_seconds INT NOT NULL,
  start_window TIMESTAMP NOT NULL,
  end_window TIMESTAMP NOT NULL,
  created_by CHAR(36),
  FOREIGN KEY (created_by) REFERENCES users(id)
);

CREATE TABLE exam_templates (
  exam_id CHAR(36) NOT NULL,
  template_id CHAR(36) NOT NULL,
  question_order INT NOT NULL,
  PRIMARY KEY (exam_id, template_id),
  FOREIGN KEY (exam_id) REFERENCES exams(id) ON DELETE CASCADE,
  FOREIGN KEY (template_id) REFERENCES question_templates(id)
);

CREATE TABLE exam_attempts (
  id CHAR(36) PRIMARY KEY,
  exam_id CHAR(36),
  student_id CHAR(36),
  started_at TIMESTAMP NULL,
  submitted_at TIMESTAMP NULL,
  status VARCHAR(20) DEFAULT 'NOT_STARTED',
  score INT,
  total_questions INT,
  FOREIGN KEY (exam_id) REFERENCES exams(id),
  FOREIGN KEY (student_id) REFERENCES users(id),
  UNIQUE (exam_id, student_id)
);

CREATE TABLE question_variants (
  id CHAR(36) PRIMARY KEY,
  template_id CHAR(36),
  exam_attempt_id CHAR(36),
  variable_values JSON NOT NULL,
  rendered_text TEXT NOT NULL,
  correct_answer NUMERIC NOT NULL,
  options JSON NOT NULL,
  correct_index INT NOT NULL,
  question_order INT NOT NULL,
  FOREIGN KEY (template_id) REFERENCES question_templates(id),
  FOREIGN KEY (exam_attempt_id) REFERENCES exam_attempts(id)
);

CREATE TABLE student_answers (
  id CHAR(36) PRIMARY KEY,
  attempt_id CHAR(36),
  variant_id CHAR(36),
  selected_index INT,
  is_correct BOOLEAN,
  time_spent_seconds INT,
  answered_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (attempt_id) REFERENCES exam_attempts(id),
  FOREIGN KEY (variant_id) REFERENCES question_variants(id)
);

CREATE TABLE flag_events (
  id CHAR(36) PRIMARY KEY,
  attempt_id CHAR(36),
  event_type VARCHAR(30) NOT NULL,
  occurred_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (attempt_id) REFERENCES exam_attempts(id)
);

CREATE TABLE revision_sets (
  id CHAR(36) PRIMARY KEY,
  attempt_id CHAR(36) UNIQUE,
  weak_topics JSON NOT NULL,
  generated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (attempt_id) REFERENCES exam_attempts(id)
);

CREATE TABLE revision_questions (
  revision_set_id CHAR(36) NOT NULL,
  variant_id CHAR(36) NOT NULL,
  PRIMARY KEY (revision_set_id, variant_id),
  FOREIGN KEY (revision_set_id) REFERENCES revision_sets(id) ON DELETE CASCADE,
  FOREIGN KEY (variant_id) REFERENCES question_variants(id)
);

CREATE TABLE topic_stats (
  id CHAR(36) PRIMARY KEY,
  template_id CHAR(36) UNIQUE,
  times_answered INT DEFAULT 0,
  times_correct INT DEFAULT 0,
  difficulty_index NUMERIC,
  discrimination_index NUMERIC,
  last_calibrated TIMESTAMP NULL,
  FOREIGN KEY (template_id) REFERENCES question_templates(id)
);
